version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://deakin_library_1012_user:UHqXTTFcOSE1T5YNF7KhQolwPl3vZBFW@dpg-cre5vrogph6c73eo3shg-a.oregon-postgres.render.com/deakin_library_1012

  inventory_management:
    build:
      context: ./inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://deakin_library_1012_user:UHqXTTFcOSE1T5YNF7KhQolwPl3vZBFW@dpg-cre5vrogph6c73eo3shg-a.oregon-postgres.render.com/deakin_library_1012
