apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: deakinlibrary.azurecr.io/project_part3-book_catalog:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://deakin_library_1012_user:UHqXTTFcOSE1T5YNF7KhQolwPl3vZBFW@dpg-cre5vrogph6c73eo3shg-a.oregon-postgres.render.com/deakin_library_1012"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8000
  type: LoadBalancer
